# Generated by Django 6.0.2 on 2026-05-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0003_seasonalpricerange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonalpricerange',
            name='season',
            field=models.CharField(choices=[('spring', 'Spring  (Mar-May)'), ('summer', 'Summer  (Jun-Aug)'), ('autumn', 'Autumn  (Sep-Nov)'), ('winter', 'Winter  (Dec-Feb)')], max_length=10),
        ),
    ]
