# Generated by Django 6.0.2 on 2026-05-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='wilaya',
            field=models.CharField(blank=True, help_text='الولاية التي تتوفر فيها الآلة', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipmentrequest',
            name='admin_note',
            field=models.TextField(blank=True, help_text='ملاحظة الـ admin عند القبول أو الرفض'),
        ),
        migrations.AlterField(
            model_name='equipmentrequest',
            name='reason',
            field=models.TextField(help_text='سبب طلب الآلة'),
        ),
    ]
