# Generated by Django 6.0.2 on 2026-05-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipment_price_name_ar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('tractor', 'Tractor'), ('harvester', 'Harvester'), ('plow', 'Plow'), ('seeder', 'Seeder'), ('sprayer', 'Sprayer'), ('irrigation', 'Irrigation System'), ('baler', 'Baler'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='equipmentrequest',
            name='admin_note',
            field=models.TextField(blank=True, help_text='Admin note on approval or rejection'),
        ),
        migrations.AlterField(
            model_name='equipmentrequest',
            name='reason',
            field=models.TextField(help_text='Reason for requesting the equipment'),
        ),
        migrations.AlterField(
            model_name='equipmentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
    ]
