# Generated by Django 6.0.4 on 2026-04-13 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransporterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=100)),
                ('capacity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_areas', models.TextField(help_text='Comma-separated list of wilayas / regions')),
                ('is_available', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transporter_profile', to='accounts.customuser')),
            ],
        ),
    ]
