# Generated by Django 6.0.2 on 2026-05-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='shipping_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price set by transporter before accepting', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_wilaya',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Farmer Approval'), ('pending', 'Open — Awaiting Transporter'), ('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('declined', 'Declined')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Farmer Approval'), ('confirmed', 'Confirmed by Farmer'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
